name: first_workflow

on: push

jobs:
  runs_on_command:
    runs-on: ubuntu-latest
    steps:
      - name: list all files
        run: ls -a
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: make
      run: |
            mkdir big
            echo "hello world"
            touch app.js
            echo "console.log("hello")" > app.js
            cat aspp.js
            ls -a
      
      
