name: first_workflow

on: push

env:
  GLOBAL: variable

jobs:
  runs_on_command:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(env) }}'
      - run: echo '${{ toJSON(github) }}'
      - run: echo $GLOBAL
