name: first_workflow

on: push
env:
    GLOBAL:"varaible"
jobs:
  runs_on_command:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{env}}
      - run: echo ${{github}}
      - run: echo $GLOBAL
   
